#pragma once
#include "../maze.hpp"
#include <random>
// ============================================================================
// LoopGenerator
// ============================================================================
// Breaks the "perfect maze" generated by Prim's algorithm by randomly smashing
// walls to create circular paths and loops, increasing the confusion and
// chaotic feeling of the Backrooms.
//
// Time Complexity: O(V) where V is the total number of grid cells. It does a
// single, simple linear scan across the entire maze grid.
// ============================================================================
class LoopGenerator {
public:
    void generate(Maze& maze, std::mt19937& rng);
};
