#pragma once
#include "../maze.hpp"
#include <random>
// ============================================================================
// LoopGenerator
// ============================================================================
// Breaks the "perfect maze" generated by Prim's algorithm by randomly smashing
// walls to create circular paths and loops, increasing the confusion and
// chaotic feeling of the Backrooms.
// ============================================================================
class LoopGenerator {
public:
    void generate(Maze& maze, std::mt19937& rng);
};
