#pragma once
// ==== pal ====
// The master palette as raylib Colors. GENERATED by tools/palette_header.py
// from assets/palette.json - edit the JSON, re-run the tool, never this file.
// Each ramp runs dark -> light from step 0. assets/palette_strip.png holds the
// same colours in the same order (ramp after ramp), which is what the test
// PaletteHeader.MatchesStrip compares against.

#include "raylib.h"

namespace pal {

inline constexpr int neutralSteps = 8;
inline constexpr Color neutral[8] = {
    Color{ 20,  21,  23, 255},  //  0 #141517
    Color{ 46,  46,  46, 255},  //  1 #2e2e2e
    Color{ 70,  70,  70, 255},  //  2 #464646
    Color{ 98,  98,  98, 255},  //  3 #626262
    Color{126, 126, 126, 255},  //  4 #7e7e7e
    Color{156, 156, 156, 255},  //  5 #9c9c9c
    Color{189, 189, 189, 255},  //  6 #bdbdbd
    Color{217, 217, 218, 255},  //  7 #d9d9da
};

inline constexpr int greySteps = 8;
inline constexpr Color grey[8] = {
    Color{ 29,  28,  39, 255},  //  0 #1d1c27
    Color{ 56,  56,  71, 255},  //  1 #383847
    Color{ 71,  72,  88, 255},  //  2 #474858
    Color{ 87, 100, 119, 255},  //  3 #576477
    Color{113, 125, 143, 255},  //  4 #717d8f
    Color{130, 157, 165, 255},  //  5 #829da5
    Color{166, 183, 198, 255},  //  6 #a6b7c6
    Color{189, 213, 222, 255},  //  7 #bdd5de
};

inline constexpr int brownSteps = 8;
inline constexpr Color brown[8] = {
    Color{ 47,  25,  11, 255},  //  0 #2f190b
    Color{ 74,  42,  25, 255},  //  1 #4a2a19
    Color{102,  59,  39, 255},  //  2 #663b27
    Color{125,  76,  46, 255},  //  3 #7d4c2e
    Color{147,  99,  64, 255},  //  4 #936340
    Color{177, 122,  78, 255},  //  5 #b17a4e
    Color{204, 151, 112, 255},  //  6 #cc9770
    Color{244, 165, 104, 255},  //  7 #f4a568
};

inline constexpr int yellowSteps = 12;
inline constexpr Color yellow[12] = {
    Color{ 56,  46,  22, 255},  //  0 #382e16
    Color{ 72,  58,  32, 255},  //  1 #483a20
    Color{ 84,  69,  39, 255},  //  2 #544527
    Color{102,  89,  50, 255},  //  3 #665932
    Color{116, 101,  60, 255},  //  4 #74653c
    Color{135, 120,  74, 255},  //  5 #87784a
    Color{150, 137,  78, 255},  //  6 #96894e
    Color{167, 151,  87, 255},  //  7 #a79757
    Color{180, 172, 106, 255},  //  8 #b4ac6a
    Color{204, 190, 104, 255},  //  9 #ccbe68
    Color{232, 210, 130, 255},  // 10 #e8d282
    Color{246, 233, 152, 255},  // 11 #f6e998
};

inline constexpr int greenSteps = 8;
inline constexpr Color green[8] = {
    Color{ 15,  57,  15, 255},  //  0 #0f390f
    Color{ 22,  78,  25, 255},  //  1 #164e19
    Color{ 60, 103,  35, 255},  //  2 #3c6723
    Color{ 61, 127,  65, 255},  //  3 #3d7f41
    Color{118, 150,  60, 255},  //  4 #76963c
    Color{105, 167,  84, 255},  //  5 #69a754
    Color{145, 202,  81, 255},  //  6 #91ca51
    Color{183, 240, 116, 255},  //  7 #b7f074
};

inline constexpr int blueSteps = 6;
inline constexpr Color blue[6] = {
    Color{ 21,  45,  92, 255},  //  0 #152d5c
    Color{ 47,  72, 118, 255},  //  1 #2f4876
    Color{ 59, 101, 144, 255},  //  2 #3b6590
    Color{ 78, 145, 175, 255},  //  3 #4e91af
    Color{110, 167, 198, 255},  //  4 #6ea7c6
    Color{145, 214, 232, 255},  //  5 #91d6e8
};

inline constexpr int accentSteps = 6;
inline constexpr Color accent[6] = {
    Color{107,  38,  67, 255},  //  0 #6b2643
    Color{  6,  62, 230, 255},  //  1 #063ee6
    Color{176,  42,  42, 255},  //  2 #b02a2a
    Color{244,  54,  54, 255},  //  3 #f43636
    Color{204, 153, 255, 255},  //  4 #cc99ff
    Color{149, 218,  65, 255},  //  5 #95da41
};

inline constexpr int totalColours = 56;

// Every colour in strip order, for the conformance test and any future
// palette texture upload.
inline const Color* rampByIndex(int ramp, int& stepsOut) {
  switch (ramp) {
    case 0: stepsOut = neutralSteps; return neutral;
    case 1: stepsOut = greySteps; return grey;
    case 2: stepsOut = brownSteps; return brown;
    case 3: stepsOut = yellowSteps; return yellow;
    case 4: stepsOut = greenSteps; return green;
    case 5: stepsOut = blueSteps; return blue;
    case 6: stepsOut = accentSteps; return accent;
    default: stepsOut = 0; return nullptr;
  }
}
inline constexpr int rampCount = 7;

}  // namespace pal
