#!/usr/bin/env python3
"""Generate src/core/palette.hpp from assets/palette.json.

Usage:
    python tools/palette_header.py

Why: the sheets are held to the palette by quantize.py, but the UI, the item
glows and the fade overlays are drawn from C++ colour literals, and a literal
cannot be checked by a PNG tool. This writes the palette as constexpr raylib
Colors so C++ has no reason to spell a hex by hand. Ramps keep their JSON
names and step order (0 = darkest); roles ("text", "alert") are not here -
they are a hand decision and live in ui/ui_theme.hpp.

Re-run after any change to assets/palette.json and commit the header. The
test PaletteHeader.MatchesStrip fails if the two drift.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "palette.json")
DST = os.path.join(ROOT, "src", "core", "palette.hpp")


def main():
    with open(SRC) as f:
        ramps = json.load(f)["ramps"]
    out = ["#pragma once", "// ==== pal ====",
           "// The master palette as raylib Colors. GENERATED by tools/palette_header.py",
           "// from assets/palette.json - edit the JSON, re-run the tool, never this file.",
           "// Each ramp runs dark -> light from step 0. assets/palette_strip.png holds the",
           "// same colours in the same order (ramp after ramp), which is what the test",
           "// PaletteHeader.MatchesStrip compares against.", "",
           '#include "raylib.h"', "", "namespace pal {", ""]
    for r in ramps:
        n = len(r["colours"])
        out.append(f"inline constexpr int {r['name']}Steps = {n};")
        out.append(f"inline constexpr Color {r['name']}[{n}] = {{")
        for i, c in enumerate(r["colours"]):
            rr, g, b = c["rgb"]
            out.append(f"    Color{{{rr:3d}, {g:3d}, {b:3d}, 255}},  // {i:2d} {c['hex']}")
        out.append("};"); out.append("")
    total = sum(len(r["colours"]) for r in ramps)
    out.append(f"inline constexpr int totalColours = {total};")
    out.append("")
    out.append("// Every colour in strip order, for the conformance test and any future")
    out.append("// palette texture upload.")
    out.append("inline const Color* rampByIndex(int ramp, int& stepsOut) {")
    out.append("  switch (ramp) {")
    for i, r in enumerate(ramps):
        out.append(f"    case {i}: stepsOut = {r['name']}Steps; return {r['name']};")
    out.append("    default: stepsOut = 0; return nullptr;")
    out.append("  }")
    out.append("}")
    out.append(f"inline constexpr int rampCount = {len(ramps)};")
    out.append("")
    out.append("}  // namespace pal")
    with open(DST, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(DST, ROOT)}: {total} colours in {len(ramps)} ramps")


if __name__ == "__main__":
    main()
